language: php

php:
    - 8.1.0

env:
    matrix:
        - COMPOSER_FLAGS='--prefer-lowest'
        - COMPOSER_FLAGS='--prefer-stable'

cache:
    directories:
        - $HOME/.composer/cache/files

install:
    - composer self-update
    - composer update --no-interaction --prefer-dist $COMPOSER_FLAGS

jobs:
    include:
        - php: 8.1.0
          env: COMPOSER_FLAGS='--prefer-stable'
          script:
              - make php-cs-fixer
              - make psalm
script:
    - make phpunit
